export default {
   DEPOSIT: "DEPOSIT",
   WITHDRAWAL: "WITHDRAWAL",

   SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
   SHOW_ALL: "SHOW_ALL",
   SHOW_DEPOSITS: "SHOW_DEPOSITS",
   SHOW_WITHDRAWALS: "SHOW_WITHDRAWALS"
}